---
- name: Install NodeSource setup script
  command: curl -fsSL https://deb.nodesource.com/setup_{{ node_major }}.x | sudo -E bash -
  become: yes

- name: Install Node.js and Nginx
  apt:
    name: [nodejs, nginx]
    state: present
    update_cache: yes
  become: yes

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present
  become: yes

- name: Allow HTTP in UFW
  ufw:
    rule: allow
    port: 80
    proto: tcp
  become: yes

- name: Clone/update TravelMemory repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ project_root }}"
    version: HEAD
    update: yes
    force: yes

# Install backend dependencies
- name: Install backend dependencies
  npm:
    path: "{{ project_root }}/{{ backend_dir }}"
    production: false
  environment:
    NODE_OPTIONS: "--max-old-space-size=1024"

# Build frontend
- name: Install frontend dependencies
  npm:
    path: "{{ project_root }}/{{ frontend_dir }}"
    production: false

- name: Build frontend
  shell: "npm run build"
  args:
    chdir: "{{ project_root }}/{{ frontend_dir }}"

# Nginx config
- name: Write nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/travelmemory.conf
  become: yes

- name: Enable site and disable default
  file:
    src: /etc/nginx/sites-available/travelmemory.conf
    dest: /etc/nginx/sites-enabled/travelmemory.conf
    state: link
  become: yes

- name: Remove default site if exists
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Test and reload nginx
  shell: "nginx -t"
  register: nginx_test
  changed_when: false
  become: yes

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  when: nginx_test.rc == 0
  become: yes

# PM2 app
- name: Render PM2 ecosystem file
  template:
    src: ecosystem.config.js.j2
    dest: "{{ project_root }}/ecosystem.config.js"
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Start API with PM2
  shell: "pm2 start {{ project_root }}/ecosystem.config.js && pm2 save"
  args:
    creates: "/home/ubuntu/.pm2/dump.pm2"

- name: Enable PM2 startup on boot
  shell: "pm2 startup systemd -u ubuntu --hp /home/ubuntu"
  become: yes
